apiVersion: v1
kind: LimitRange
metadata:
  name: resource-cnstr
spec:
  limits:
    - default:
        cpu: "200m"
        memory: "128Mi"
      defaultRequest:
        cpu: "100m"
        memory: "64Mi"
      type: Container
