---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: teamup-preprod
spec:
  containers:
    - name: nginx
      image: nginx:1.21.6
      imagePullPolicy: IfNotPresent
      env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: nginx
              key: host
        - name: DB_LOGIN
          valueFrom:
            secretKeyRef:
              name: nginx
              key: login
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: nginx
              key: port
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf
        items:
          - key: nginx.conf
            path: nginx.conf
      
