---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: "4Gi"
  storageClassName: "yc-network-hdd"
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk-csi-driver.mks.ycloud.io
    fsType: ext4
    volumeHandle: fhmmqdrflmoco8gpl8od
